package com.ucc.convenios.shared.enums;

public enum ConvenioStatus {
    BORRADOR,
    EMPRESA_PENDIENTE,

    PENDIENTE_DOCUMENTOS_EMPRESA,
    DOCUMENTOS_EMPRESA_RECIBIDOS,
    DOCUMENTOS_OBSERVADOS_EMPRESA,
    DOCUMENTOS_APROBADOS,
    LISTO_PARA_RADICAR,

    RADICADO,
    EN_REVISION,
    EN_CORRECCION,
    APROBADO_PARA_FIRMA,
    FORMALIZADO,
    RECHAZADO,
    DESISTIDO,
    VENCIDO,
    CERRADO
}